<?php

########################################################################
# Extension Manager/Repository config file for ext: "jdav_sv"
#
# Auto generated by Extbase Kickstarter 2011-04-01
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'JDAV Schulungsverwaltung',
	'description' => 'Schulungsverwaltung für die JDAV Baden-Württemberg',
	'category' => 'plugin',
	'author' => 'Michael Knoll',
	'author_email' => 'mimi@kaktusteam.de',
	'author_company' => 'MKLV GbR',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>